// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0NXKMVW5aruOZ5XMZ2TQoTvzABO-Wvc',
    appId: '1:679755929816:web:0bc1958186403eb1359fad',
    messagingSenderId: '679755929816',
    projectId: 'crewin-test-project',
    authDomain: 'crewin-test-project.firebaseapp.com',
    storageBucket: 'crewin-test-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKiXpmLcM3pZabGHw1CD5SKqvz2jllGM',
    appId: '1:679755929816:android:1af8599b1b3ffd54359fad',
    messagingSenderId: '679755929816',
    projectId: 'crewin-test-project',
    storageBucket: 'crewin-test-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBey1Vum65nnBQOMI-pCrTZSUck-UGYxcA',
    appId: '1:679755929816:ios:dc0e1030493a805e359fad',
    messagingSenderId: '679755929816',
    projectId: 'crewin-test-project',
    storageBucket: 'crewin-test-project.appspot.com',
    iosClientId: '679755929816-t6l4jkkqpq24u1gnm74jb60rhsptvaqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewinOrnekProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBey1Vum65nnBQOMI-pCrTZSUck-UGYxcA',
    appId: '1:679755929816:ios:dc0e1030493a805e359fad',
    messagingSenderId: '679755929816',
    projectId: 'crewin-test-project',
    storageBucket: 'crewin-test-project.appspot.com',
    iosClientId: '679755929816-t6l4jkkqpq24u1gnm74jb60rhsptvaqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewinOrnekProje',
  );
}
