// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXGd1RecNZnv-C4vlkDgbOFqT33ikGTY',
    appId: '1:293005950606:web:c441dc8ae98bb2e525d3df',
    messagingSenderId: '293005950606',
    projectId: 'crewin-test',
    authDomain: 'crewin-test.firebaseapp.com',
    storageBucket: 'crewin-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fZbr3PASTwJiN41T3CQva_Pfw2abLI0',
    appId: '1:293005950606:android:626cfefe6e63277225d3df',
    messagingSenderId: '293005950606',
    projectId: 'crewin-test',
    storageBucket: 'crewin-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbLEf4WU5RvYVoAu_4feMOWpQLxgsMPzI',
    appId: '1:293005950606:ios:75b1743b5078986525d3df',
    messagingSenderId: '293005950606',
    projectId: 'crewin-test',
    storageBucket: 'crewin-test.appspot.com',
    iosClientId: '293005950606-jfsbev14dqv8f7h2i5q8gm2njdr6alh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbLEf4WU5RvYVoAu_4feMOWpQLxgsMPzI',
    appId: '1:293005950606:ios:75b1743b5078986525d3df',
    messagingSenderId: '293005950606',
    projectId: 'crewin-test',
    storageBucket: 'crewin-test.appspot.com',
    iosClientId: '293005950606-jfsbev14dqv8f7h2i5q8gm2njdr6alh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
